import type { HospiceKnowledgeBlock } from "./types.js";

export const HOSPICE_KNOWLEDGE_CATALOG: HospiceKnowledgeBlock[] = [

  // ─── HOSPICE FOUNDATIONS ────────────────────────────────────────────────────

  {
    id: "HF001",
    domain: "symptom_management",
    title: "What Hospice Actually Is",
    tags: ["hospice", "what is hospice", "palliative", "comfort care", "curative", "explained"],
    urgency: "routine",
    journeyStages: ["newly_enrolled", "stable"],
    summary: "Hospice is specialized medical care focused on comfort and quality of life when curative treatment is no longer the goal.",
    explanation: "Hospice is a Medicare/Medicaid benefit and model of care for people whose illness is expected to limit life to 6 months or less if the disease follows its natural course. It shifts the goal from cure to comfort — managing symptoms, supporting the family, and honoring the person's wishes.",
    whatMayBeHappening: "You or your family may have many questions about what hospice covers, who to call, and what changes to expect.",
    whatToDoNow: "Ask the hospice team for an orientation call. Request a copy of the plan of care. Know the names of your nurse, social worker, chaplain, and on-call number.",
    whatToSay: "Ask: 'Who do I call after hours? What does the comfort kit contain? What does my benefit cover? What happens if symptoms get worse?'",
    whatToWatchFor: "Poor communication, delayed callbacks, lack of proactive education — these are care gaps that should be addressed early.",
    whatNotToAssume: "Hospice does not mean giving up. It does not mean medications will be withheld. It does not mean death is imminent. It is active, expert care for a different goal.",
    whenToEscalate: "Call the hospice team whenever you have questions. That is exactly what the 24/7 line is for.",
    hardStops: [],
    relatedIds: ["HF002", "CG001"],
    sources: ["Medicare Hospice Benefit (42 CFR Part 418)", "NHPCO Standards of Practice"],
  },

  {
    id: "HF002",
    domain: "symptom_management",
    title: "The Comfort Kit and Hospice Medications",
    tags: ["comfort kit", "emergency kit", "medications", "morphine", "lorazepam", "home medications"],
    urgency: "routine",
    journeyStages: ["newly_enrolled", "stable", "weeks_to_days"],
    summary: "Every hospice patient should have a comfort kit at home with pre-approved medications to manage common end-of-life symptoms without waiting.",
    explanation: "A typical comfort kit includes: an opioid (often morphine or hydromorphone) for pain and breathlessness, a benzodiazepine (often lorazepam) for anxiety and agitation, an anticholinergic (often atropine or glycopyrrolate) for secretion management, and an antiemetic (often haloperidol) for nausea. The hospice team authorizes use and guides dosing.",
    whatMayBeHappening: "A patient may suddenly worsen and need symptom medication before the nurse can arrive.",
    whatToDoNow: "Call the hospice nurse before giving any comfort kit medication. They will authorize and guide you. Keep the kit in a designated, labeled location. Know what each medication is for.",
    whatToSay: "Tell the nurse: 'I have the comfort kit. Can you walk me through what to give for [specific symptom]?'",
    whatToWatchFor: "Running low on medications. Not knowing what the kit contains. Not having a kit at all.",
    whatNotToAssume: "Do not assume you should not give medications because you are afraid. The hospice team exists to authorize and support you. Do not wait until a crisis if symptoms are escalating.",
    whenToEscalate: "Call hospice before using the comfort kit. If symptoms are severe and the nurse does not call back within 30 minutes, call again.",
    hardStops: ["If the patient loses consciousness suddenly and this is unexpected, call 911 unless DNR is in place"],
    relatedIds: ["HF001", "SM001", "SM002"],
    sources: ["NHPCO Comfort Kit Guidelines", "AAHPM Clinical Practice Guidelines"],
  },

  {
    id: "HF003",
    domain: "care_gap",
    title: "Medicare Hospice Benefit — What Families Must Know",
    tags: ["medicare", "benefit", "covered", "pays for", "cost", "equipment", "aide", "chaplain", "social worker"],
    urgency: "routine",
    journeyStages: ["newly_enrolled", "stable"],
    summary: "The Medicare Hospice Benefit covers medications, equipment, nursing visits, aide services, social work, chaplaincy, and bereavement — understanding this helps families advocate for what they are owed.",
    explanation: "Under Medicare Part A, hospice covers: all medications related to the terminal diagnosis, medical equipment (hospital bed, wheelchair, oxygen, suction), nursing visits (frequency varies by need), home health aide services, social worker visits, chaplain visits, volunteer support, and bereavement counseling for 13 months after death. Inpatient care is available for uncontrolled symptoms or caregiver crisis.",
    whatMayBeHappening: "Families often do not know what they are entitled to and may not receive what the benefit covers unless they ask.",
    whatToDoNow: "Request a written summary of your benefit. Ask for a care conference. Request aide services if you are not getting them. Ask about inpatient respite if caregiver is overwhelmed.",
    whatToSay: "Ask: 'We would like weekly aide visits — when can that start? We need a hospital bed — how do we arrange delivery? What inpatient options are available if things get worse at home?'",
    whatToWatchFor: "Not receiving social worker visits. No chaplain contact when requested. Delays in equipment. Medications being billed separately.",
    whatNotToAssume: "Do not assume the hospice is proactively delivering everything. Some families must ask explicitly for what they are entitled to.",
    whenToEscalate: "If services promised in the plan of care are not being delivered, contact the hospice administrator. If unresolved, contact your state hospice licensure authority.",
    hardStops: [],
    relatedIds: ["HF001", "CG001", "CG002"],
    sources: ["Medicare Hospice Benefit (CMS Publication 02154)", "42 CFR § 418.202"],
  },

  // ─── DYING PROCESS ──────────────────────────────────────────────────────────

  {
    id: "DP001",
    domain: "dying_process",
    title: "Weeks to Days — Signs of Natural Decline",
    tags: ["weeks", "days", "decline", "sleeping more", "eating less", "withdrawing", "end of life", "what to expect"],
    urgency: "moderate",
    journeyStages: ["weeks_to_days"],
    summary: "When someone begins withdrawing, sleeping most of the day, and eating very little, the body is entering a natural phase of shutting down — this is expected and can be managed comfortably.",
    explanation: "In the weeks-to-days phase, natural changes include: dramatic increase in sleep (16-20+ hours per day), loss of interest in food and fluids, social withdrawal and reduced communication, increased confusion or vivid dreaming, periods of agitation or restlessness, and mottling (blotchy skin) beginning in the feet and knees.",
    whatMayBeHappening: "The body is conserving energy and slowly shutting down non-essential functions. This is a natural process, not starvation or suffering.",
    whatToDoNow: "Keep offering small sips of fluid and ice chips if the person can swallow safely. Stop pushing food — the body does not need it and forcing can cause distress. Keep the room comfortable, quiet, and familiar. Focus on presence, not activities.",
    whatToSay: "You can say: 'We're right here with you. You don't need to do anything. Just rest.' Even if they don't respond, they can often hear you.",
    whatToWatchFor: "New onset severe pain, breathing changes, sudden agitation, fever, mottling spreading to the torso and hands.",
    whatNotToAssume: "Do not assume they are hungry because they are not eating. Do not assume they are uncomfortable because they are sleeping. Do not force fluids or nutrition.",
    whenToEscalate: "Call hospice if: pain appears poorly controlled, breathing changes significantly, agitation begins, or you feel unsure about what you are seeing.",
    hardStops: [],
    relatedIds: ["DP002", "DP003", "SM001"],
    sources: ["NHPCO Clinical Practice Guidelines for Quality Palliative Care", "Ferris FD et al. Palliative Care Canada"],
  },

  {
    id: "DP002",
    domain: "dying_process",
    title: "Days — Active Dying: What to Expect",
    tags: ["active dying", "days", "mottling", "breathing changes", "Cheyne-Stokes", "unresponsive", "coma-like", "death rattle"],
    urgency: "urgent",
    journeyStages: ["days"],
    summary: "Active dying typically involves unresponsiveness, dramatic breathing changes, and circulatory shutdown — these signs indicate death is likely within 1-3 days.",
    explanation: "Signs of active dying: unresponsive to voice or touch, jaw relaxation and mouth breathing, Cheyne-Stokes respiration (rhythmic cycles of rapid breathing then stopping), mottling spreading to the torso and knees, extremities cold and dark, terminal secretions (gurgling breathing caused by secretions pooling in the throat — the patient is not choking), decreased or no urine output.",
    whatMayBeHappening: "The cardiovascular and respiratory systems are shutting down. Blood pressure and oxygen levels cannot be meaningfully maintained. This is the natural completion of the dying process.",
    whatToDoNow: "Call your hospice nurse now — do not wait. Keep the mouth moist with a damp swab. Stop all medications except those for comfort. Gentle repositioning every few hours. Gather family if appropriate. Create a peaceful environment. Speak gently — hearing is often the last sense to go.",
    whatToSay: "Speak directly to the dying person: 'We love you. We are here. You can go when you're ready. We will be okay.'",
    whatToWatchFor: "Extended apnea periods (breathing stops for 45+ seconds), jaw dropping, hands and feet turning very dark or blue.",
    whatNotToAssume: "Do not assume they cannot hear. Do not assume the secretion sounds mean they are suffocating — they are not conscious of it. Do not assume you must do anything specific beyond being present.",
    whenToEscalate: "Call hospice now. A nurse should be available by phone 24/7. If breathing becomes severely labored and comfort medications are not helping, request an urgent visit.",
    hardStops: ["If this is a sudden unexpected change (not a gradual decline), call 911 unless DNR is clearly in place"],
    relatedIds: ["DP001", "DP003", "TOD001", "SM003"],
    sources: ["Ellershaw J, Ward C. Care of the dying patient: the last hours or days of life. BMJ 2003", "NHPCO Facts and Figures"],
  },

  {
    id: "DP003",
    domain: "dying_process",
    title: "Final Moments — Signs Death Is Imminent Within Hours",
    tags: ["hours", "imminent", "final", "dying now", "breathing stopped", "last breath", "what to expect at death"],
    urgency: "critical",
    journeyStages: ["hours", "at_death"],
    summary: "In the final hours, breathing becomes very irregular and eventually stops — being present, calm, and grounded is the most important thing you can do.",
    explanation: "Final signs within hours: breathing becomes very slow and irregular with extended pauses, the jaw may drop and mouth stays open, hands and feet are very dark and cold, mottling may reach the torso, eyes may be partially open and unfocused, there is no response to voice or touch. Death occurs when breathing stops and does not resume.",
    whatMayBeHappening: "The brainstem is releasing its hold on respiratory function. The heart will stop within minutes after breathing stops.",
    whatToDoNow: "Stay in the room if you can. Hold a hand if you want. Continue speaking softly. You do not need to do anything except be present. After breathing stops, wait a few minutes before calling anyone — it is okay to have a moment.",
    whatToSay: "There are no wrong words. You might say: 'I love you. You did beautifully. We will carry you with us always.'",
    whatToWatchFor: "After the last breath — watch for chest to remain still and no sounds of breathing for 1-2 minutes.",
    whatNotToAssume: "Do not panic. This is what a peaceful death looks like. It is not violent. It is not a medical emergency if you are in hospice care.",
    whenToEscalate: "After death, call your hospice nurse. They will guide you through the next steps. Do not call 911 unless instructed or unless DNR is not in place.",
    hardStops: ["If a DNR/POLST is NOT in place and the family does not want comfort-focused care, call 911 immediately"],
    relatedIds: ["DP002", "TOD001", "AD001"],
    sources: ["Hallenbeck J. Palliative Care Perspectives. Oxford University Press", "Kübler-Ross E. On Death and Dying"],
  },

  // ─── SYMPTOM MANAGEMENT ─────────────────────────────────────────────────────

  {
    id: "SM001",
    domain: "symptom_management",
    title: "Pain Management in Hospice",
    tags: ["pain", "pain scale", "morphine", "opioid", "breakthrough", "scheduled", "uncontrolled pain"],
    urgency: "urgent",
    journeyStages: ["stable", "weeks_to_days", "days", "hours"],
    summary: "Pain is expected and highly controllable in hospice — no one should die in uncontrolled pain.",
    explanation: "Hospice uses scheduled opioids for baseline pain control and breakthrough (PRN) doses for acute pain spikes. Common medications include oral morphine, hydromorphone, and oxycodone — or transdermal fentanyl for stable needs. Breakthrough doses are typically 10-15% of the total daily dose. Dosing is adjusted until comfort is achieved.",
    whatMayBeHappening: "Pain can worsen as disease progresses. Undertreated pain is a care gap — it should never be accepted as inevitable.",
    whatToDoNow: "Score pain on a 0-10 scale. If patient is nonverbal, use the PAINAD scale. Call hospice if pain is 7/10 or above and not responding to breakthrough medication. Document time, dose given, and response.",
    whatToSay: "Tell the nurse: 'Pain is at [score]. I gave [medication and dose] at [time]. After 30 minutes it is still [score]. I need guidance on what to do next.'",
    whatToWatchFor: "Pain rating above 6/10 not responding to scheduled and breakthrough doses. New location of pain (may suggest new problem). Grimacing, moaning, or furrowing brow in a nonverbal patient.",
    whatNotToAssume: "Do not assume pain is just part of dying that must be endured. Do not skip breakthrough doses to avoid addiction — end-of-life opioid use is appropriate medical care.",
    whenToEscalate: "Call hospice any time pain is above 6/10 and not controlled by current regimen. Request a medication adjustment.",
    hardStops: ["Sudden severe headache with neck stiffness — call 911", "Sudden bone pain after a fall — may be fracture, call hospice immediately"],
    relatedIds: ["SM002", "HF002", "CG004"],
    sources: ["AAHPM/HPNA Joint Practice Guidelines for Opioid Use in Palliative Care", "Portenoy RK. JPSM 1999"],
  },

  {
    id: "SM002",
    domain: "symptom_management",
    title: "Breathlessness and Dyspnea in Hospice",
    tags: ["breathing", "breathlessness", "dyspnea", "shortness of breath", "air hunger", "oxygen", "breathing difficulty"],
    urgency: "urgent",
    journeyStages: ["stable", "weeks_to_days", "days", "hours"],
    summary: "Breathlessness is one of the most distressing hospice symptoms and is highly treatable with opioids, positioning, airflow, and anxiolytics — call hospice immediately if it is severe.",
    explanation: "Dyspnea in hospice has multiple causes: fluid accumulation (CHF, malignant effusion), airway obstruction, anemia, anxiety, and general weakness. Low-dose opioids reduce the subjective distress of breathlessness even when they do not increase oxygen saturation. A fan blowing cool air on the face activates trigeminal receptors and is clinically proven to reduce air hunger.",
    whatMayBeHappening: "The patient may feel air hunger — a frightening sensation. The goal is comfort, not oxygenation numbers.",
    whatToDoNow: "Position patient upright (head of bed elevated 30-45 degrees). Point a small fan toward the face at low speed. Loosen any tight clothing. Call hospice nurse for medication guidance. Use prescribed opioid for air hunger. Anxiolytic (lorazepam) if anxiety is contributing.",
    whatToSay: "Stay calm — your calm is contagious. Say: 'I'm right here. Try to breathe with me. In through your nose, out through your mouth. I've called the nurse.'",
    whatToWatchFor: "Breathing rate above 30/min, labored breathing with neck muscle use, cyanosis (bluish lips or fingers), extreme agitation with breathing distress.",
    whatNotToAssume: "Do not assume more oxygen always helps — in some conditions it can increase distress. Do not assume it will resolve on its own if severe. Do not give a DNR patient CPR if breathing stops — that is the natural process.",
    whenToEscalate: "Call hospice immediately for severe or sudden breathlessness. Request an urgent visit if not improving with phone guidance.",
    hardStops: ["Sudden respiratory distress with chest pain — call 911 unless comfort-measures-only order is clear"],
    relatedIds: ["SM001", "HF002", "DP002", "DM002"],
    sources: ["Abernethy AP et al. BMJ 2003 (fan for dyspnea)", "Bruera E. JPSM 1990 (opioids for dyspnea)"],
  },

  {
    id: "SM003",
    domain: "symptom_management",
    title: "Terminal Agitation and Restlessness",
    tags: ["agitation", "restlessness", "terminal restlessness", "delirium", "confused", "picking", "moaning", "calling out"],
    urgency: "urgent",
    journeyStages: ["days", "hours", "weeks_to_days"],
    summary: "Terminal agitation near death is distressing for families but treatable — it is caused by brain changes, not pain, and responds to specific medications.",
    explanation: "Terminal restlessness occurs in 25-88% of dying patients. Causes include hypoxia, metabolic changes (uremia, hyperammonemia), retained secretions, full bladder or bowel, uncontrolled pain, medication withdrawal, and brain changes from the dying process. It is treated with haloperidol, midazolam, or phenobarbital — not higher opioid doses alone. The patient is typically not conscious of the distress.",
    whatMayBeHappening: "Possible causes include urinary retention, constipation, uncontrolled pain, or neurological changes of dying. Rule out treatable causes first.",
    whatToDoNow: "Call hospice nurse NOW. While waiting: reduce stimulation in the room, use soft calm voice, check whether patient last urinated or had a bowel movement, check for obvious pain, ensure comfort kit is accessible.",
    whatToSay: "Say to the patient: 'I'm here. You're safe. I've got you.' Even if they don't respond, a familiar voice can reduce agitation.",
    whatToWatchFor: "Picking at the air or bedclothes, moaning or calling out, trying to get out of bed, facial grimacing, rhythmic movements.",
    whatNotToAssume: "Do not assume moaning means pain — it can be a neurological reflex. Do not assume more opioid is always the answer. Do not leave the patient alone when agitated.",
    whenToEscalate: "Call hospice immediately. Do not attempt to manage severe agitation without nurse guidance. This is a clinical emergency that requires medication adjustment.",
    hardStops: ["If patient falls out of bed during agitation — call hospice and assess for injury before moving"],
    relatedIds: ["SM001", "DP002", "HF002", "DM005"],
    sources: ["Lawlor PG et al. Arch Intern Med 2000", "Bush SH et al. J Pain Symptom Manage 2014"],
  },

  {
    id: "SM004",
    domain: "symptom_management",
    title: "Terminal Secretions (Death Rattle)",
    tags: ["death rattle", "secretions", "gurgling", "noisy breathing", "secretion sounds", "throat sounds"],
    urgency: "moderate",
    journeyStages: ["days", "hours"],
    summary: "The gurgling sound from secretions pooling in the throat is not painful to the patient — the patient is not choking, but the sound is distressing to family.",
    explanation: "Terminal secretions occur when a dying patient can no longer cough or clear secretions. The sound is caused by secretions vibrating in the upper airway. The patient is deeply unconscious or nearly so and does not experience choking. Treated with anticholinergics (glycopyrrolate, atropine drops, hyoscine) that reduce secretion production.",
    whatMayBeHappening: "The patient's cough and swallowing reflexes have reduced or stopped as part of the dying process.",
    whatToDoNow: "Reposition the patient on their side (lateral position) to allow gravity to help drain secretions. Call hospice nurse for anticholinergic medication authorization. Do not attempt to suction oral secretions in a deeply unconscious patient — this is more distressing than helpful.",
    whatToSay: "Tell family: 'This sound is hard to hear, but I want you to know it is not distressing to her/him. They are not choking. This is a natural part of the process. The medication will help reduce the sound.'",
    whatToWatchFor: "Medication typically reduces but does not eliminate the sound within 30-60 minutes. If sound worsens dramatically with new wet quality, call hospice.",
    whatNotToAssume: "Do not assume the patient is suffering or choking. Do not assume suctioning is helpful — it stimulates the gag reflex and can increase distress.",
    whenToEscalate: "Call hospice for medication guidance. This is a comfort measure, not an emergency, but warrants prompt attention.",
    hardStops: [],
    relatedIds: ["DP002", "DP003", "SM003"],
    sources: ["Wildiers H et al. J Pain Symptom Manage 2009", "NHPCO Clinical Practice Guidelines"],
  },

  {
    id: "SM005",
    domain: "symptom_management",
    title: "Confusion and Delirium",
    tags: ["confusion", "delirium", "delirious", "disoriented", "not making sense", "hallucinations", "seeing things"],
    urgency: "urgent",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Delirium in hospice is common and often reversible — dehydration, medications, constipation, and infection are common causes that warrant a call to hospice.",
    explanation: "Delirium is characterized by acute confusion, disorientation, fluctuating consciousness, and sometimes hallucinations or paranoia. In hospice, common causes include: opioid toxicity, dehydration, urinary retention, constipation, infection (UTI, pneumonia), metabolic changes, and brain metastases. Near death, 'terminal delirium' is not reversible. Hypoactive delirium (quiet confusion) is often missed.",
    whatMayBeHappening: "A treatable cause may be present. Call hospice before assuming this is irreversible.",
    whatToDoNow: "Call hospice nurse to assess. Keep environment calm and simple — one person speaking at a time. Do not argue with or correct delusions. Offer gentle orienting cues (time, place, familiar voices). Ensure safety: bed rails up, clutter cleared, walkways safe.",
    whatToSay: "Speak slowly and clearly: 'It's [name]. You're at home. It's safe here. I'm right here with you.' Do not say 'No, that's not real' — it increases agitation.",
    whatToWatchFor: "Sudden severe confusion (versus gradual), paranoid or violent behavior, inability to recognize family.",
    whatNotToAssume: "Do not assume confusion is permanent before hospice evaluates. Do not leave a delirious patient alone near stairs, sharp objects, or doorways.",
    whenToEscalate: "Call hospice for any new or worsening confusion. Request a nurse visit if possible.",
    hardStops: ["If patient becomes violent or a safety risk — call 911 for safety regardless of DNR status"],
    relatedIds: ["SM003", "DP002"],
    sources: ["Inouye SK. NEJM 2006", "Leonard M et al. Palliative Medicine 2008"],
  },

  {
    id: "SM006",
    domain: "symptom_management",
    title: "Nausea and Vomiting",
    tags: ["nausea", "vomiting", "sick to stomach", "antiemetic", "ondansetron", "haloperidol"],
    urgency: "moderate",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Nausea is treatable in hospice and should never be left unmanaged — multiple medication options exist.",
    explanation: "Common causes in hospice: opioid-induced nausea (often resolves in 3-5 days as tolerance develops), constipation, bowel obstruction, brain metastases, metabolic imbalances, and gastric stasis. First-line agents include ondansetron (for most causes), haloperidol (especially opioid-induced or metabolic), metoclopramide (for gastric stasis), and dexamethasone (for bowel obstruction or brain-related).",
    whatMayBeHappening: "A new opioid or opioid dose increase commonly causes transient nausea. Constipation is frequently overlooked as a nausea cause.",
    whatToDoNow: "Check when the patient last had a bowel movement — constipation must be ruled out first. Avoid strong food smells. Offer small amounts of clear liquids. Call hospice for antiemetic prescription if not already in comfort kit.",
    whatToSay: "Ask the nurse: 'They are nauseated and last had a bowel movement [X days] ago. What antiemetic would you recommend and should we also address constipation?'",
    whatToWatchFor: "Vomiting large amounts, coffee-ground appearance (digested blood), abdominal distension or rigidity — all warrant urgent hospice call.",
    whatNotToAssume: "Do not assume nausea is just part of dying and cannot be treated. Do not assume the opioid must be stopped for nausea — antiemetics usually solve opioid-induced nausea.",
    whenToEscalate: "Call hospice for persistent vomiting that prevents medication administration. Call immediately for signs of bowel obstruction (severe cramping, distended abdomen).",
    hardStops: ["Coffee-ground or bloody vomiting — call hospice immediately, may require call to 911"],
    relatedIds: ["SM001", "HF002"],
    sources: ["Herndon CM, Jackson KC. Pharmacotherapy 2002", "Twycross R. Palliative Care Formulary"],
  },

  // ─── URGENT RED FLAGS ────────────────────────────────────────────────────────

  {
    id: "RF001",
    domain: "urgent_red_flag",
    title: "Red Flags: Call 911 Even with DNR",
    tags: ["911", "emergency", "trauma", "fall", "fracture", "bleed", "stroke", "fire", "safety"],
    urgency: "critical",
    journeyStages: ["stable", "weeks_to_days", "days", "hours"],
    summary: "A DNR order does not mean you cannot call 911 — call 911 for safety emergencies, falls with injury, fire, violence, or situations the hospice team cannot manage.",
    explanation: "DNR/POLST orders address cardiac and respiratory resuscitation only. Emergency services can still be called for: safety threats (fall with suspected fracture, violence), fire or environmental emergency, caregiver medical emergency, a patient requesting emergency care despite prior wishes, or any situation beyond the immediate capacity of the hospice team.",
    whatMayBeHappening: "A crisis has arisen that cannot wait for the hospice nurse to arrive.",
    whatToDoNow: "Call 911 for any of: major fall with suspected injury, fire or home emergency, violence or safety threat, caregiver collapse, patient suddenly requesting resuscitation against prior plan.",
    whatToSay: "When calling 911, tell them: 'This is a hospice patient. The DNR/POLST is posted at [location]. The emergency is [describe].' Hand them the DNR document when they arrive.",
    whatToWatchFor: "Sudden unexplained change in consciousness not in the context of gradual expected decline.",
    whatNotToAssume: "Do not assume the DNR prevents all emergency calls. Do not assume you must manage every crisis alone.",
    whenToEscalate: "Call 911 immediately for the situations above.",
    hardStops: ["Major trauma or fall — call 911", "Fire — call 911", "Caregiver collapse — call 911", "Violence — call 911"],
    relatedIds: ["HF001", "DP002", "DP003"],
    sources: ["NHPCO Position Statement on Emergency Response", "CMS Hospice Guidance Manual"],
  },

  {
    id: "RF002",
    domain: "urgent_red_flag",
    title: "Sudden Uncontrolled Bleeding",
    tags: ["bleeding", "hemorrhage", "blood", "coughing blood", "rectal bleed", "wound bleed", "massive bleed", "catastrophic"],
    urgency: "critical",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Catastrophic hemorrhage is a rare but known risk in some hospice diagnoses — preparation and dark-colored towels can help manage a terminal bleed.",
    explanation: "Massive hemorrhage can occur with: head/neck cancers eroding large vessels, lung cancer with hemoptysis, esophageal varices, rectal cancer, and others. A terminal hemorrhage is typically not survivable. The goal is managing the scene to reduce trauma for the family. Hospice should have prepared the family with a 'just in case' plan.",
    whatMayBeHappening: "If this is occurring: it is likely a terminal event if massive. Your priority is your safety and the patient's comfort.",
    whatToDoNow: "Call 911 AND hospice simultaneously if this is happening. Apply firm pressure with dark towels if accessible. Stay with the patient. If the patient is unconscious, this may be the final moments. If they are conscious — stay calm, hold their hand, speak quietly and reassuringly.",
    whatToSay: "Stay with the patient. Say: 'I'm right here. I'm not going anywhere.' Call for help.",
    whatToWatchFor: "If the hospice team identified the patient as high-risk for catastrophic bleed, they should have provided a plan and dark-colored supplies.",
    whatNotToAssume: "Do not assume you did something wrong. This is a disease complication. Do not leave the patient alone.",
    whenToEscalate: "Call 911 and hospice simultaneously for any sudden large bleed.",
    hardStops: ["Call 911 AND hospice simultaneously"],
    relatedIds: ["RF001", "DP003"],
    sources: ["Harris DG et al. Palliative Medicine 2011", "NHPCO Catastrophic Hemorrhage Guidelines"],
  },

  // ─── MIDDLE OF THE NIGHT ─────────────────────────────────────────────────────

  {
    id: "MN001",
    domain: "middle_of_night",
    title: "Middle of the Night — When Everything Feels Worse",
    tags: ["middle of the night", "3am", "night", "can't sleep", "afraid", "alone", "night fear", "panic"],
    urgency: "moderate",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Fear and crisis feel most acute in the dark — calling the hospice after-hours line at 2am is exactly what it is there for.",
    explanation: "Caregiver exhaustion peaks at night. Symptoms that feel manageable during the day often feel catastrophic at 2am. Every hospice must provide 24/7 phone access by CMS regulation. The after-hours nurse is clinically prepared and expects these calls. You are not bothering them. Middle-of-night calls often prevent unnecessary 911 calls and unnecessary hospitalizations.",
    whatMayBeHappening: "You may be exhausted, frightened, and unsure whether what you are seeing is normal or an emergency.",
    whatToDoNow: "Call the hospice 24/7 line. Take a breath before you dial. Have the patient's name, medications, and what you're seeing ready to describe. You do not need to know if it's serious — that is for the nurse to assess.",
    whatToSay: "Say: 'This is [your name]. I'm calling about [patient name] who is on your hospice service. It's [time] and I'm seeing [describe what you see]. I'm not sure if I should be worried, but I needed to call.'",
    whatToWatchFor: "Any change in breathing, level of consciousness, new pain, or any symptom you have not seen before.",
    whatNotToAssume: "Do not assume you should wait until morning. Do not assume you are overreacting. Night fear is real and valid.",
    whenToEscalate: "Call hospice now. If you cannot reach them within 30 minutes, call again or go to an emergency room.",
    hardStops: ["If the patient stops breathing unexpectedly — call hospice. If no DNR — call 911."],
    relatedIds: ["HF001", "DP002", "CG001"],
    sources: ["42 CFR § 418.204 (After-Hours Requirement)", "NHPCO Quality Standards"],
  },

  {
    id: "MN002",
    domain: "middle_of_night",
    title: "Caregiver Crisis at Night — Overwhelm and Exhaustion",
    tags: ["overwhelmed", "exhausted", "can't do this", "alone at night", "caregiver burnout", "need help", "I'm scared"],
    urgency: "moderate",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Caregiver burnout and nighttime panic are medical issues — hospice social workers and respite care exist specifically for this.",
    explanation: "Hospice caregivers often push through exhaustion until they hit a breaking point — frequently at night. Unaddressed caregiver distress leads to 911 calls, hospitalizations, and poor patient care. Hospice is required to provide respite care (inpatient or residential stay of up to 5 days) and social worker support.",
    whatMayBeHappening: "You may have reached the limit of what one person can do. This is not weakness — it is human.",
    whatToDoNow: "Call the hospice line. Tell them you need support. Ask for a social worker call. Ask about respite care options. Call a family member or friend to come be with you tonight if possible.",
    whatToSay: "Tell the hospice nurse: 'I need to be honest — I am not okay. I am exhausted and frightened and I am not sure I can do this tonight. What support is available to me right now?'",
    whatToWatchFor: "If you are having thoughts of harming yourself — call 988 (Suicide and Crisis Lifeline) immediately.",
    whatNotToAssume: "Do not assume you must handle this alone. Do not assume asking for help is giving up.",
    whenToEscalate: "Call hospice now if you are not able to safely care for the patient tonight.",
    hardStops: ["Thoughts of self-harm — call 988 immediately"],
    relatedIds: ["CG001", "CG002", "HF003"],
    sources: ["NHPCO Family Caregiver Survey", "42 CFR § 418.106 (Respite Care)"],
  },

  // ─── COMMUNICATION COACHING ──────────────────────────────────────────────────

  {
    id: "CC001",
    domain: "communication_coaching",
    title: "Talking to a Hospice Nurse — SBAR Structure",
    tags: ["SBAR", "calling hospice", "talking to nurse", "reporting", "how to call", "prepare for call"],
    urgency: "moderate",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Using SBAR (Situation, Background, Assessment, Request) helps you communicate clearly and quickly with hospice nurses.",
    explanation: "SBAR is the standard clinical communication format. A well-structured call gets faster, better responses. Hospice nurses are trained to receive SBAR calls and will often prompt you through it.",
    whatMayBeHappening: "You need to communicate something to the nurse and want to be clear and organized.",
    whatToDoNow: "Before calling: write down (1) What is happening right now in 1-2 sentences, (2) The patient's diagnosis and recent history, (3) Your assessment of how serious it is, (4) Exactly what you need from the team.",
    whatToSay: "S: 'This is [name] calling about [patient]. She is experiencing [symptom] that started [when].' B: 'She has [diagnosis]. Her usual medications are [X]. She has been [stable/declining].' A: 'Her pain is [score]. Her breathing is [description].' R: 'I need [guidance/visit/medication authorization/someone to come].'",
    whatToWatchFor: "If the nurse dismisses your concern without adequate guidance, say: 'I want to make sure I have a clear plan. Can you tell me exactly what to watch for and when to call back?'",
    whatNotToAssume: "Do not assume the nurse knows your specific situation without you telling them. Do not apologize for calling — you are entitled to this support.",
    whenToEscalate: "If the call does not resolve your concern, ask to speak with the charge nurse or on-call physician.",
    hardStops: [],
    relatedIds: ["CC002", "CG003"],
    sources: ["Institute for Healthcare Improvement — SBAR Communication Tool"],
  },

  {
    id: "CC002",
    domain: "communication_coaching",
    title: "Talking to Family Members About What Is Happening",
    tags: ["family meeting", "telling family", "explaining dying", "having the conversation", "family communication"],
    urgency: "moderate",
    journeyStages: ["weeks_to_days", "days", "hours", "stable"],
    summary: "Families often need permission to hear the truth — honest, compassionate communication prevents family conflict and supports peaceful dying.",
    explanation: "Family communication about dying is often avoided until it is too late. The most helpful stance is direct but compassionate: naming what is happening, naming the timeline, naming what the person needs now. Hospice social workers are trained to facilitate family meetings.",
    whatMayBeHappening: "Some family members may not know or accept that their loved one is dying. This can create conflict about care decisions.",
    whatToDoNow: "Request a hospice social worker family meeting. Before the meeting: agree with your hospice team on what information will be shared. Prepare for some family members to respond with anger, denial, or grief.",
    whatToSay: "Say: 'I know this is hard to hear. The doctors and hospice team believe that [name] is in the last [days/weeks] of their life. Our job now is to make sure they are comfortable and feel loved and not alone. What can we do together to give them that?'",
    whatToWatchFor: "Family conflict about care goals, pressure to seek curative treatment, family members requesting actions inconsistent with the patient's wishes.",
    whatNotToAssume: "Do not assume everyone will accept the information the same way. Do not assume conflict means people don't care — it usually means they care too much.",
    whenToEscalate: "Request a social worker visit if family conflict is affecting care.",
    hardStops: [],
    relatedIds: ["CC001", "CC003", "GB001"],
    sources: ["Back AL et al. Approaching Difficult Conversations in Medicine. JAMA 2003"],
  },

  {
    id: "CC003",
    domain: "communication_coaching",
    title: "Explaining Death to Children",
    tags: ["children", "child", "kids", "grandchildren", "explaining death to child", "what to tell kids"],
    urgency: "moderate",
    journeyStages: ["weeks_to_days", "days", "after_death", "bereavement"],
    summary: "Children understand more than adults often assume — honest, age-appropriate language and inclusion in the dying process helps more than it harms.",
    explanation: "Children younger than 5 need simple, concrete language. School-age children (5-12) can understand death is permanent and may have intense questions. Teenagers may grieve through anger or withdrawal. All ages benefit from being allowed to participate in saying goodbye, being involved in rituals, and having their grief taken seriously.",
    whatMayBeHappening: "Children may be left out of the dying process to protect them, which often creates more fear and confusion.",
    whatToDoNow: "Use honest, concrete language: 'Grandpa is very sick and his body is going to stop working soon. He is going to die. That means we won't be able to see him or hug him anymore, but we will always love him and miss him.' Let them ask questions. Let them see the person if they want to.",
    whatToSay: "Avoid: 'passed away', 'went to sleep', 'gone to a better place' — these can create fear of sleep and confusion. Use 'died' and 'death' gently but clearly.",
    whatToWatchFor: "Behavioral changes in children: school refusal, sleep disturbances, regression, withdrawal, or unusual aggression — these are grief signals.",
    whatNotToAssume: "Do not assume children are too young to understand or to grieve. Do not assume they are fine just because they're playing.",
    whenToEscalate: "Ask the hospice social worker for child-specific grief resources and referrals. School counselors can be excellent support.",
    hardStops: [],
    relatedIds: ["CC002", "GB004"],
    sources: ["Worden JW. Children and Grief. Guilford Press 2018", "Winston's Wish Child Bereavement Guidelines"],
  },

  // ─── TIME OF DEATH ───────────────────────────────────────────────────────────

  {
    id: "TOD001",
    domain: "time_of_death",
    title: "When Death Occurs — First Steps",
    tags: ["death occurred", "just died", "I think they died", "what to do after death", "who to call", "just passed"],
    urgency: "urgent",
    journeyStages: ["at_death"],
    summary: "When death occurs, you do not need to rush — take a moment, then call the hospice line, not 911, unless instructed otherwise.",
    explanation: "At the time of death in a hospice setting: a nurse will come to pronounce death (timing varies, sometimes up to 2 hours). The body does not need to be moved immediately. The funeral home typically waits for the nurse. You have time to sit with your loved one, say goodbye, and notify family.",
    whatMayBeHappening: "Death has occurred after a period of decline. This is a profoundly important moment.",
    whatToDoNow: "Step 1: Take a breath. You do not need to act immediately. Step 2: Call the hospice 24/7 line. Tell them '[Name] has died. I am at home with them.' Step 3: Wait for the nurse's guidance on next steps. Step 4: Call family when you are ready. Step 5: Do not call the funeral home until the hospice nurse has pronounced death.",
    whatToSay: "There are no required words. You might say: 'We love you. You were everything to us. Rest now.'",
    whatToWatchFor: "The nurse will check for absence of pulse and breathing to pronounce death officially.",
    whatNotToAssume: "Do not call 911 unless a DNR is NOT in place or you are unsure. Do not feel rushed to call the funeral home.",
    whenToEscalate: "If you cannot reach hospice within 30 minutes and you are unsure what to do, call 911 and show them the DNR document.",
    hardStops: ["If NO DNR is in place and the patient stops breathing — call 911"],
    relatedIds: ["AD001", "DP003"],
    sources: ["NHPCO After-Death Guidance for Families", "CMS Hospice Manual"],
  },

  // ─── AFTER DEATH ─────────────────────────────────────────────────────────────

  {
    id: "AD001",
    domain: "after_death",
    title: "The Hours After Death — What Happens Next",
    tags: ["after death", "funeral home", "body", "pronouncement", "next steps", "death certificate", "medications disposal"],
    urgency: "moderate",
    journeyStages: ["after_death"],
    summary: "After death at home, there is time — the body does not need to be rushed away, the nurse will guide you, and most practical steps can happen over hours, not minutes.",
    explanation: "Typical sequence: (1) Family time with the body — there is no required wait time, most families take 1-3 hours. (2) Hospice nurse arrives to pronounce death and complete paperwork. (3) Hospice will contact the physician for the death certificate. (4) Family contacts the funeral home when ready. (5) Medications must be disposed of — hospice will advise on safe disposal (DEA guidelines require supervised disposal of controlled substances).",
    whatMayBeHappening: "The family is in shock, grief, or a strange calm. All of these are normal responses.",
    whatToDoNow: "Take the time you need with your loved one. Notify people at your own pace. Do not feel pressured by anyone to act faster than you are ready. When the hospice nurse arrives, they will guide the next steps.",
    whatToSay: "You do not need to say anything to anyone right now. When you are ready, you might say: 'They died peacefully at home. We were with them.'",
    whatToWatchFor: "Hospice will contact you within 24 hours to discuss bereavement services. Keep all hospice contact information — they remain your resource.",
    whatNotToAssume: "Do not assume you must immediately call extended family. Do not assume the medications must be disposed of immediately — just secure them away from others.",
    whenToEscalate: "If the hospice nurse has not arrived within 2 hours and the funeral home is pressing you, call the hospice main line.",
    hardStops: [],
    relatedIds: ["TOD001", "GB001", "AD002"],
    sources: ["NHPCO Family Guide to Hospice Care After Death", "DEA Medication Disposal Guidelines"],
  },

  {
    id: "AD002",
    domain: "after_death",
    title: "Medication Disposal After Death",
    tags: ["medication disposal", "unused drugs", "controlled substances", "morphine disposal", "after death medications"],
    urgency: "moderate",
    journeyStages: ["after_death"],
    summary: "Controlled substances must be disposed of safely after death — the hospice nurse or a local DEA-authorized disposal site can help.",
    explanation: "DEA regulations require controlled substances (opioids, benzodiazepines) be disposed of within a reasonable time. Options: hospice nurse can document and dispose under DEA regulations during the death visit; local law enforcement or pharmacy take-back programs; FDA-approved drug deactivation pouches (mix and flush). Do not simply flush controlled substances unless no other option exists and the drug label or patient insert specifically authorizes flushing.",
    whatMayBeHappening: "There may be medications remaining in the comfort kit or prescription bottles.",
    whatToDoNow: "Set all medications aside in a secure location until the hospice nurse arrives. Ask the nurse: 'Can you help us dispose of the medications before you leave?'",
    whatToSay: "You do not need to explain the medications to family or guests — simply secure them.",
    whatToWatchFor: "Do not leave medications accessible to children, pets, or visitors.",
    whatNotToAssume: "Do not assume medications should simply be thrown in the trash — this is environmentally harmful and creates diversion risk.",
    whenToEscalate: "If the hospice nurse cannot help with disposal, call your local pharmacy or law enforcement for a take-back program.",
    hardStops: [],
    relatedIds: ["AD001", "HF002"],
    sources: ["DEA Office of Diversion Control — Medication Disposal Guidelines", "FDA Safe Medication Disposal Program"],
  },

  // ─── GRIEF AND BEREAVEMENT ───────────────────────────────────────────────────

  {
    id: "GB001",
    domain: "grief_bereavement",
    title: "Anticipatory Grief — Grieving Before the Death",
    tags: ["anticipatory grief", "grief before death", "anticipating loss", "already mourning", "grieving while still alive"],
    urgency: "routine",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Grieving while someone is still alive is normal, healthy, and not a betrayal — anticipatory grief is how humans prepare for profound loss.",
    explanation: "Anticipatory grief includes: sadness, crying, anger, guilt, depression, anxiety about the future, and even relief — all while the person is still living. Studies show anticipatory grief can reduce acute grief reactions after death and helps families make meaning and complete relationships. It is not a sign of giving up hope.",
    whatMayBeHappening: "You may be experiencing waves of grief while also providing care and maintaining daily life.",
    whatToDoNow: "Allow yourself to grieve. Find at least one person to talk to honestly about your feelings — a friend, counselor, or support group. Ask the hospice social worker for a referral. If you have a spiritual practice, lean into it.",
    whatToSay: "You might say to others: 'I'm grieving this person even while they're still here. I'm grieving what we had, what we won't have, and the future I imagined. And that's okay.'",
    whatToWatchFor: "If grief is completely disabling your daily function — preventing eating, sleeping, or safe caregiving — call your doctor or a mental health professional.",
    whatNotToAssume: "Do not assume grieving early means you love them less. Do not assume you must be strong all the time.",
    whenToEscalate: "Ask for a hospice social worker visit for emotional support. Request a bereavement counselor if available.",
    hardStops: [],
    relatedIds: ["GB002", "GB003", "CG001"],
    sources: ["Rando TA. Loss and Anticipatory Grief. Lexington Books 1986", "Johansson AK. Palliative & Supportive Care 2012"],
  },

  {
    id: "GB002",
    domain: "grief_bereavement",
    title: "Grief After Death — Shock, Guilt, and Relief",
    tags: ["grief after death", "guilt", "relief", "shock", "I feel relief", "did I do enough", "did I do the right thing"],
    urgency: "moderate",
    journeyStages: ["after_death", "bereavement"],
    summary: "Feeling relief after a death does not mean you didn't love them — it is a natural response to the end of suffering and of caregiving.",
    explanation: "Common grief experiences after a hospice death: shock and numbness even when death was expected, guilt about decisions made, intense relief that suffering has ended, relief mixed with guilt about the relief, replaying the final hours or days, wondering if something could have been done differently. All of these are normal.",
    whatMayBeHappening: "Your mind and body are processing an enormous loss while also releasing the enormous stress of caregiving.",
    whatToDoNow: "Allow yourself to feel whatever you feel without judgment. Rest. Eat. Allow others to care for you. Consider a bereavement support group.",
    whatToSay: "If others express surprise at your reaction: 'Grief is different for everyone. I loved them deeply. I'm also relieved they are no longer suffering. Both are true.'",
    whatToWatchFor: "Signs of complicated grief or clinical depression: inability to function after several weeks, hopelessness, thoughts of self-harm. These warrant professional support.",
    whatNotToAssume: "Do not assume relief means you are a bad person. Do not assume all grief looks like crying.",
    whenToEscalate: "Thoughts of self-harm — call 988. Inability to function after several weeks — call your doctor.",
    hardStops: ["Thoughts of self-harm — call 988 immediately"],
    relatedIds: ["GB001", "GB003", "AD001"],
    sources: ["Shear MK. Complicated Grief. NEJM 2015", "NHPCO Bereavement Standards"],
  },

  {
    id: "GB003",
    domain: "grief_bereavement",
    title: "Caregiver Grief and Exhaustion After the Death",
    tags: ["caregiver grief", "after death exhaustion", "caregiver burnout", "now what", "empty", "identity after caregiving"],
    urgency: "moderate",
    journeyStages: ["after_death", "bereavement"],
    summary: "Caregivers often experience profound disorientation and emptiness after death — their identity has been built around caregiving for months or years.",
    explanation: "Caregiver grief has a unique quality: the loss of purpose, structure, and identity that caregiving provided. Many caregivers report feeling useless, lost, or without direction after the death. Physical exhaustion may take weeks to lift. The house may feel unbearably quiet. These feelings are normal and expected.",
    whatMayBeHappening: "The adrenaline of caregiving has stopped and grief and exhaustion are flooding in.",
    whatToDoNow: "Give yourself time to rest — truly rest. Do not make major decisions (moving, selling property) in the first few months. Stay connected to at least one person who knew the person you lost. Call the hospice bereavement team — they must offer 13 months of bereavement follow-up.",
    whatToSay: "It is okay to say: 'I don't know who I am right now. I was their caregiver for so long. I need help figuring out what comes next.'",
    whatToWatchFor: "Complete isolation, inability to eat or sleep, prolonged inability to function.",
    whatNotToAssume: "Do not assume you should be over this quickly. Do not assume you will feel this way forever.",
    whenToEscalate: "Contact the hospice bereavement team. Consider joining a caregiver bereavement group.",
    hardStops: [],
    relatedIds: ["GB001", "GB002", "CG001"],
    sources: ["Schulz R. Caregiver Burden and Bereavement. Archives of Internal Medicine 2001"],
  },

  // ─── CAREGIVER SUPPORT ───────────────────────────────────────────────────────

  {
    id: "CG001",
    domain: "caregiver_support",
    title: "Caregiver Burnout — Signs and What to Do",
    tags: ["caregiver burnout", "exhaustion", "overwhelmed", "I can't do this", "I need help", "respite"],
    urgency: "moderate",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Caregiver burnout is real and dangerous — for both the caregiver and the patient. Asking for help is the most important thing you can do.",
    explanation: "Signs of caregiver burnout: physical exhaustion despite adequate sleep, emotional numbness or rage, withdrawing from friends or family, neglecting your own health, feeling trapped or hopeless, increasing mistakes in caregiving. Burnout affects care quality. Hospice is required to offer respite care (5 days inpatient per Medicare benefit period).",
    whatMayBeHappening: "You have been carrying too much for too long without adequate support.",
    whatToDoNow: "Call the hospice social worker today — do not wait. Ask explicitly: 'I need respite care. What options are available this week?' Ask family to cover specific shifts. Accept help when offered.",
    whatToSay: "Say directly: 'I have reached my limit. I need support. What can we arrange immediately?'",
    whatToWatchFor: "Caregiver illness, accidents due to fatigue, any thought of self-harm.",
    whatNotToAssume: "Do not assume asking for help means you love them less. Do not assume you can push through indefinitely.",
    whenToEscalate: "Call hospice social worker now if you are at your limit. Call 988 if you are having thoughts of self-harm.",
    hardStops: ["Thoughts of self-harm — call 988 immediately"],
    relatedIds: ["CG002", "HF003", "MN002"],
    sources: ["Family Caregiver Alliance — Caregiver Health", "AARP Caregiver Research Center"],
  },

  {
    id: "CG002",
    domain: "caregiver_support",
    title: "When to Ask for Respite Care",
    tags: ["respite", "inpatient respite", "break", "relief", "caregiver break", "hospice facility"],
    urgency: "moderate",
    journeyStages: ["stable", "weeks_to_days"],
    summary: "Respite care — a short inpatient stay — is a Medicare-covered hospice benefit that gives caregivers a necessary break.",
    explanation: "Medicare hospice benefit includes up to 5 consecutive days of inpatient respite care per benefit period. The patient stays in a Medicare-approved facility (usually a nursing home or hospice inpatient unit) and receives the same care. The caregiver gets a break. Many caregivers avoid using this because they feel guilty — this should not be the case.",
    whatMayBeHappening: "You may have reached a point where you physically or emotionally cannot continue without a break.",
    whatToDoNow: "Contact your hospice social worker or case manager and say: 'I need to discuss respite care options.' They will coordinate placement.",
    whatToSay: "If you feel guilty, remind yourself: 'Taking this break makes me a better caregiver. My loved one is still getting excellent care. I am protecting both of us.'",
    whatToWatchFor: "Insurance may limit respite to specific facilities — ask about options in advance before you are in crisis.",
    whatNotToAssume: "Do not assume you must be completely unable to function before asking for respite. You can be proactive.",
    whenToEscalate: "If the hospice social worker is unresponsive to your respite request, contact the hospice administrator.",
    hardStops: [],
    relatedIds: ["CG001", "HF003"],
    sources: ["42 CFR § 418.108 (Respite Care)", "Medicare Hospice Benefit Guidance"],
  },

  {
    id: "CG003",
    domain: "caregiver_support",
    title: "Preparing to Call Hospice — Be Organized, Not Perfect",
    tags: ["calling hospice", "prepare call", "what to say", "organized", "reporting symptoms"],
    urgency: "moderate",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "You don't need to have all the answers before calling hospice — just tell them what you see.",
    explanation: "Many caregivers delay calling hospice because they are afraid of 'bothering' the nurse or not knowing the right words. The hospice line exists for exactly these calls. You only need to describe what you observe.",
    whatMayBeHappening: "A symptom or change is worrying you.",
    whatToDoNow: "Before calling, jot down: (1) What changed. (2) When it started. (3) What medications you have given. (4) What you need (guidance, visit, medication adjustment). Then call.",
    whatToSay: "Open with: 'I'm calling about [patient name]. Something has changed and I want to make sure I'm doing the right thing.'",
    whatToWatchFor: "Do not wait until a symptom becomes severe. Early calls prevent crisis.",
    whatNotToAssume: "Do not assume you are overreacting. Err on the side of calling.",
    whenToEscalate: "Any time you are unsure — call.",
    hardStops: [],
    relatedIds: ["CC001", "HF001"],
    sources: ["NHPCO Family Education Guidelines"],
  },

  {
    id: "CG004",
    domain: "caregiver_support",
    title: "Documentation — What to Track and Why",
    tags: ["documentation", "journal", "tracking", "symptoms log", "write down", "when did this start"],
    urgency: "routine",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Keeping a simple symptom log helps hospice nurses make better decisions and gives you a clearer picture of how things are changing.",
    explanation: "A symptom log does not need to be elaborate. Track: date/time, symptom, severity (0-10 scale), what medication was given, and response. This information helps nurses adjust medications, identify patterns, and make urgent decisions faster.",
    whatMayBeHappening: "Symptoms may be changing gradually in ways that are hard to remember without a record.",
    whatToDoNow: "Start a simple paper or phone log. At minimum: date/time, what symptom occurred, what you gave, and what happened after.",
    whatToSay: "When calling hospice, say: 'My log shows that pain has been averaging 6/10 for the past three days with breakthrough doses wearing off at about 2 hours.'",
    whatToWatchFor: "Patterns that suggest medications need adjustment.",
    whatNotToAssume: "Do not assume you will remember — write it down.",
    whenToEscalate: "Bring your log to every nurse visit. Share entries when calling after hours.",
    hardStops: [],
    relatedIds: ["CC001", "SM001"],
    sources: ["NHPCO Caregiver Education Series"],
  },

  // ─── CARE GAPS ───────────────────────────────────────────────────────────────

  {
    id: "CGAP001",
    domain: "care_gap",
    title: "Poor Hospice Education — You Were Never Told What to Expect",
    tags: ["no one explained", "no one told me", "not prepared", "what to expect", "wasn't told", "not educated"],
    urgency: "moderate",
    journeyStages: ["newly_enrolled", "stable", "weeks_to_days"],
    summary: "Every hospice patient and family is entitled to thorough education — if you were not taught what to expect, that is a care gap you can address right now.",
    explanation: "Hospice regulations require comprehensive family education on: what changes to expect, how to use medications, comfort care techniques, when to call, what the dying process looks like, and what to do at the time of death. If this education has not happened, it is not too late to ask.",
    whatMayBeHappening: "You were enrolled in hospice but never received the education you needed.",
    whatToDoNow: "Call the hospice and request a nurse visit specifically for education. Ask for: information about the dying process, how to use the comfort kit, what to do when death occurs, and what you should expect in the coming weeks.",
    whatToSay: "Say directly: 'We feel like we were not adequately prepared for what is happening. We would like a comprehensive teaching visit as soon as possible.'",
    whatToWatchFor: "If the hospice responds with excuses or delays, document the conversation and escalate to the administrator.",
    whatNotToAssume: "Do not assume you should already know this. This is the hospice's job to teach you.",
    whenToEscalate: "If education is repeatedly deferred, contact your state hospice licensure office.",
    hardStops: [],
    relatedIds: ["HF001", "HF002", "DA001"],
    sources: ["42 CFR § 418.116 (Hospice Education Requirements)", "NHPCO Quality Standards"],
  },

  {
    id: "CGAP002",
    domain: "care_gap",
    title: "Delayed Callbacks and After-Hours Non-Response",
    tags: ["no callback", "not calling back", "waiting for nurse", "after hours not responding", "can't reach hospice"],
    urgency: "urgent",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Hospice must provide 24/7 phone access — a callback delay over 30 minutes for an urgent call is a regulatory violation.",
    explanation: "CMS requires hospice to provide continuous access to nursing advice 24/7. An after-hours nurse must be available by phone at all times. Delayed or absent callbacks for urgent calls violate 42 CFR § 418.204 and should be documented and reported.",
    whatMayBeHappening: "You are in a crisis and the hospice is not responding.",
    whatToDoNow: "If no callback in 30 minutes for an urgent issue: call again, document the time. If still no response: call the hospice main office number and ask to speak with a supervisor. If still no response and the situation is urgent: call 911.",
    whatToSay: "Say: 'I called at [time] with an urgent concern about my hospice patient. I have not received a callback. I need a nurse now.'",
    whatToWatchFor: "Document every call: date, time, who you spoke with, what they said.",
    whatNotToAssume: "Do not assume they will call back eventually. Do not wait beyond 30 minutes for an urgent situation.",
    whenToEscalate: "Contact the hospice administrator. File a complaint with your state hospice licensure office if this is a pattern.",
    hardStops: ["Immediate safety emergency — call 911 regardless"],
    relatedIds: ["MN001", "HF001", "DA001"],
    sources: ["42 CFR § 418.204 (After-Hours Requirement)", "CMS Hospice Survey Guidance"],
  },

  {
    id: "CGAP003",
    domain: "care_gap",
    title: "Symptom Management Gap — Pain or Distress Not Being Controlled",
    tags: ["undertreated pain", "uncontrolled symptoms", "they said wait", "pain not controlled", "breathlessness not treated"],
    urgency: "urgent",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "No hospice patient should experience prolonged uncontrolled pain or distress — if your concerns are being dismissed, escalate immediately.",
    explanation: "Undertreated pain and breathlessness are quality failures and potential regulatory violations. NHPCO quality standards require ongoing assessment and medication adjustment. If the hospice nurse says 'just wait' or 'that's normal' without a plan, that is not acceptable.",
    whatMayBeHappening: "The current medication regimen is not adequate for the current level of disease or symptoms.",
    whatToDoNow: "Document the current pain or symptom score. Call hospice and demand a medication adjustment conversation with the nurse AND the hospice physician. Say you want a concrete plan, not reassurance.",
    whatToSay: "Say: 'I need to speak with someone who can authorize a medication change. The current medications are not controlling [pain/breathlessness/agitation]. This is not acceptable. What is the plan for today?'",
    whatToWatchFor: "Nurses who offer reassurance without a plan. Physicians who are unreachable.",
    whatNotToAssume: "Do not assume undertreated symptoms are inevitable. They are a care failure.",
    whenToEscalate: "Contact the hospice medical director. File a complaint with the state agency if symptoms remain uncontrolled.",
    hardStops: [],
    relatedIds: ["SM001", "SM002", "DA001", "CGAP002"],
    sources: ["NHPCO Quality Standards", "Joint Commission Hospice Standards"],
  },

  // ─── DOCUMENTATION AND ADVOCACY ──────────────────────────────────────────────

  {
    id: "DA001",
    domain: "documentation_advocacy",
    title: "How to Document Care Failures and Escalate",
    tags: ["document", "complaint", "escalate", "file complaint", "state agency", "care failure", "bad hospice care"],
    urgency: "moderate",
    journeyStages: ["stable", "weeks_to_days", "days"],
    summary: "Documenting care failures creates accountability and is the first step to improving care for your family and future families.",
    explanation: "Documentation that matters: date/time of calls and visits, names of staff contacted, what was reported and what was said, what actions were taken and what was promised. Formal escalation path: (1) Hospice nurse supervisor. (2) Hospice administrator. (3) State hospice licensure office (Medicaid/Medicare certification). (4) CMS regional office. (5) Accreditation body (CHAP, ACHC, or Joint Commission).",
    whatMayBeHappening: "Your concerns are not being addressed through normal channels.",
    whatToDoNow: "Start a written log immediately. Keep all names, dates, and times. Write down exact quotes when possible. Send follow-up emails or texts to create a written record. Ask for a care conference with the hospice administrator.",
    whatToSay: "Say: 'I am documenting this conversation. I would like confirmation in writing of the plan we have discussed.'",
    whatToWatchFor: "Defensive responses, promises without follow-through, attempts to minimize concerns.",
    whatNotToAssume: "Do not assume your complaint will not make a difference — it protects other families.",
    whenToEscalate: "If a care conference with the administrator does not resolve the issue, contact your state health department.",
    hardStops: [],
    relatedIds: ["CGAP002", "CGAP003"],
    sources: ["CMS Hospice Survey Guidance Manual", "State Ombudsman Programs"],
  },

];

export function getBlockById(id: string): HospiceKnowledgeBlock | undefined {
  return HOSPICE_KNOWLEDGE_CATALOG.find((b) => b.id === id);
}

export function getBlocksByDomain(domain: string): HospiceKnowledgeBlock[] {
  return HOSPICE_KNOWLEDGE_CATALOG.filter((b) => b.domain === domain);
}
